# NABSTRACT CONFIDENTIAL
#
# Copyright 2022-2023 Nabstract Technologies Private Limited.
#
# This software and the related documents are Nabstract copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Nabstract's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

# Default values for NEF.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: nabstract

# enable toleration for this POD to run on the K8S master
enable_toleration: false

image:
  repository: docker.io/devnio/nef
  tag: "2.5.7"
  pullPolicy: IfNotPresent

service:
  name: nefservice
  type: NodePort

configmap:
  name: configmapNEF
  nef: nef-cm
  oauth2: oauth2-cm
  certs: certs-cm

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

#Agent
agent:
  image: registry.redhat.io/rhosdt/opentelemetry-collector-rhel8:0.74.0-4
  #image: devnio/opentelemetry-collector-dev:latest
  configmapName: otel-nef-agent-config-vol
  configMap: otel-nef-agent-conf
  name: otel-nef-agent
  rootca:  /root/CA/cert.pem
  servername: otel-collector.telemetry.svc
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  opencensusport: 55678  #OpenCensus receiver port
  receivers: opencensus
  receiver:
    opencensus:
      endpoint: localhost:55678
  
  exporters: opencensus
  exporter:
    opencensus:
      endpoint: otel-collector.telemetry.svc:55668
