# NABSTRACT CONFIDENTIAL
#
# Copyright 2022-2023 Nabstract Technologies Private Limited.
#
# This software and the related documents are Nabstract copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Nabstract's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: nabstract
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nef-role 
subjects:
- kind: ServiceAccount
  name: nef 
  namespace: nabstract
