# NABSTRACT CONFIDENTIAL
#
# Copyright 2022-2023 Nabstract Technologies Private Limited.
#
# This software and the related documents are Nabstract copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Nabstract's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    {{- include "nef-nabstract.labels" . | nindent 4 }}
  namespace: "{{ .Values.namespace }}"
spec:
  type: ClusterIP
  ports:
    - port: 8060
      #nodePort: 31573
      targetPort: 8060
      protocol: TCP
      name: af
    - port: 9051
      #nodePort: 31574
      targetPort: 9051
      protocol: TCP
      name: notification
  selector:
    {{- include "nef-nabstract.selectorLabels" . | nindent 4 }}
